### ISSUE TITLE
How to add this extension to chorme ?

### ISSUE THREAD

**Issue by karthicguru** [prince-mishra/flipkart-seller-filter#1]
I have tried to convert it as crx file and import at chrome://extensions page.. But it throws some error .. any thing else i have to do?

**Comment by prince-mishra** [comment]
Import the code into chrome in developer mode. That should be easier to do. I didn't try making a crx myself.

**Comment by prince-mishra** [comment]
making a crx for distribution is not on the cards. The best doc is here : https://github.com/prince-mishra/flipkart-seller-filter/blob/master/README.md
