### ISSUE TITLE
Doesn't filter after a number of products

### ISSUE THREAD

**Issue by ghost** [prince-mishra/flipkart-seller-filter#2]
Tried searching Power Bank in fkart with WS Retail as Seller Filter.
The top products were greyed out, but after that all the products were back to normal.
At first I thought all those are WS Retail products, but when individual products are clicked they're from a diff seller

**Comment by prince-mishra** [comment]
@ipridvi you will have to click on the search button again. The greying out works only on the items visible at the time search was clicked. As you scroll down, fk keeps adding items, which the extension doesn't yet filter out. I'll add this as a feature in next version.
