### ISSUE TITLE
Sorry to open up an issue here

### ISSUE THREAD

**Issue by lawnet** [prince-mishra/flipkart-seller-filter#5]
You replied to me in this repo ( https://github.com/rozdoum/social-app-android ) about some code of download image. Can you share that?

**Comment by prince-mishra** [comment]
Heyy - I have been traveling. Will share as soon as I get near my computer (a couple of days more)

**Comment by lawnet** [comment]
Hey... Are you back ?  Kind of stuck at that part badly.
